### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#10]
I already sent you some suggestions by emails, but let's now switch to git to keep track of them:

- [x] toggle on/off the electrodes numbers
- [x] I agree that the color of the selected cluster should be highlighted in the TraceView.
- [x] The GUI should work without the datafile (thus no TraceView)
- [x] In the TraceView, have a command to be able to jump to a particular time
- [x] There is a bug when switching the Waveform view to Mean view (with w). The zoom level is not kept in my case
- [x] The number of waveform to select from each cluster should be configured (see #12)
- [ ] or alternatively display them only in the local area of the template. Because for high channel count > 252, the GUI take ages to open. We already spoke about that, but we could plot only Traces from the channels involved in a given templates, or in a selected regions drawn on the probe design by the user (see #11)
- [ ] And as we spoke, the possibility to click on a spike in the TraceView to get the appropriate cluster would be great (see #8)

How are the spike colorcoded in the TraceView. How do you decide that the color is applied or not? If there is a spike, you do not color all channels belonging to the template, but only a subset. How is this subset chosen?

Otherwise, this is great ! Happy to make the switch from MATLAB soon !!

**Comment by rossant** [comment]
I took the liberty to reorganize the list and open separate issues. Some of them are already implemented in https://github.com/kwikteam/phy/pull/683

> How are the spike colorcoded in the TraceView. How do you decide that the color is applied or not? If there is a spike, you do not color all channels belonging to the template, but only a subset. How is this subset chosen?

There is a mask threshold, 0.5 by default. For any given spike, if the spike is higher on a given channel, it is highlighted, otherwise it is not. The color is random if the spike isn't selected (fixed for a given cluster and during the entire session), or blue/red/whatever if the cluster is selected (the color depends on whether the cluster is the first selected, second, etc.)

**Comment by yger** [comment]
Just to mention that even with last release, the bug about the scaling in the WaveformView is still here. I mean, when pressing W, to toggle the mean view, the zoom level is lost, and I have to use Ctrl a lot to get something visible....

**Comment by rossant** [comment]
even with master branch of phy and phycontrib??

**Comment by yger** [comment]
Yes. Maybe this is the dataset? I'll try with an other one. But basically,
pressing W bring me almost flat curves, and I need to use Ctrl a lot to
bring them back

Pierre

2016-04-01 9:54 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by yger** [comment]
Just double checked, this is not the dataset, same with a new one. Is there a computation performed to define the zoom, or could it be related tothe way I'm storing the data ? I must say that means are correct, just way smaller than waveforms

**Comment by rossant** [comment]
Ah I have misunderstood your problem then. This is not what I fixed... Can you make a screenshot and explain precisely what happens?

**Comment by rossant** [comment]
wait I think I know what it is, there may be a hard-coded value of 200x for KiloSort between the waveforms and the templates (as part of the whitening). Try to tweak it directly in phycontrib/template/gui.py maybe, until I implement a proper fix

**Comment by yger** [comment]
Ok, I'll have a look, even if I do not see a hard-coded 200 value in phycontrib/template/gui.py. No hurry, I just wanted to keep the issue alive...

I'll search more in depth myself. My simple problem is that, if this is my waveform view

![before](https://cloud.githubusercontent.com/assets/1672447/14201488/96147b62-f7f2-11e5-8431-8ee19d4e4bad.png)

This is what it becomes by pressing W. There is a scaling issue somewhere

![after](https://cloud.githubusercontent.com/assets/1672447/14201486/96038c30-f7f2-11e5-80a0-43c09dfbe19d.png)

**Comment by rossant** [comment]
hmm I may have already fixed this actually by incorporating the scaling factor directly in the whitening matrix (line 291). I think you should have a look at this matrix and double check that it doesn't introduce a scaling factor...? Another thing is that the templates are scaled by the mean amplitude. See line 412.

**Comment by nippoo** [comment]
I remember implementing a scaling factor of about 15x between templates and waveforms for SpykingCircus display (in the previous phy version), which was reasonable. I never ended up finding a good way of figuring out the optimal scaling - I guess some sort of crude median amplitude matching would probably work...

**Comment by yger** [comment]
But where does this factor come from???? In the MATLAB GUI, we do not need any factor, and the same data (waveforms in the whitened space and templates) can be superimposed, as you would expect. What could be wrong here ? The templates are in the whitened space, could it be the reason ? But what you are displaying by pressing W is is the template, or the real mean on the waveforms ? Could the two be superimposed ? I do not understand...

**Comment by yger** [comment]
By the way, good to hear you are giving a try to Spyking CIRCUS! Hope you managed to get it running rather smoothly, and if you have feedback to give, do not hesitate! My suggestion so far is to mostly use a lot of CPUs instead of GPU.... 
Otherwise, coming back to phy-contrib, the GUI is now rather fast even for 252 channels, so I'm really happy with it, you are doing an amazing job! Next challenge, 4225 ;-)

**Comment by rossant** [comment]
@yger I need to check but I may not use the same space for the waveforms and templates (?) cc @nsteinme there might be an issue opened about it

also I haven't done my optimizations yet! I'm currently doing low-level work in `phy.plot` to make many optimizations on the CPU

**Comment by yger** [comment]
I know the core optimizations are not made! I'm sure the complete workflow at the end will be very cool, I'm just too impatient :-) I'll read the gui.py code to see if I can spot something puzzling, maybe I'm not exporting the data as you are doing with KiloSort.

**Comment by nsteinme** [comment]
Yes we had a discussion about this kilosort factor of 200, the resolution
is that I remove the factor (from the whitening matrix) before saving the
data for phy.

However I just checked and whereas my templates have amplitudes like 0.3,
the raw data is in units of µV so spikes have amplitudes like 50 to 1000.
However it occurs to me that there is an ambiguity between the templates
and the amplitudes: you could multiply your templates by 2 and divide all
your amplitudes by 2 and the fit to the data would be the same. I believe
Marius's templates are normalized, maybe Pierre makes a different decision?
However I think this isn't the total accounting - when I scale the
templates by the amplitudes they still aren't big enough to match the raw
data by about a factor of 10 probably. I will ask Marius.

Nick

**Comment by nippoo** [comment]
Might be worth splitting this off into a separate issue...

**Comment by yger** [comment]
In our case, we are saving the templates, not normalized, such that an
amplitude of 1 is exactly a perfect fit onto the raw data (whitened of
course). This is why there is something strange here, so yes, I'll create
an issue

2016-04-01 14:54 GMT+02:00 Max Hunter <notifications@github.com>:
